[package]
name = "slinker"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
description = "Target-specific linker for installed R package images"
license = "BSD-3-Clause"
publish = false

[[bin]]
name = "slinker"
path = "src/main.rs"
required-features = ["air"]

[features]
default = ["air"]
air = ["dep:air_r_parser", "dep:air_r_syntax", "dep:biome_rowan", "dep:rayon"]

[dependencies]
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
rayon = { version = "1.12", optional = true }
air_r_parser = { git = "https://github.com/posit-dev/air", tag = "0.11.0", optional = true }
air_r_syntax = { git = "https://github.com/posit-dev/air", tag = "0.11.0", optional = true }

biome_rowan = { git = "https://github.com/lionel-/biome", rev = "a1296ea6ba363d8b8d8f02181b2a4ce9315c5ef9", optional = true }

